source "https://rubygems.org"

gem 'jekyll', '~> 4'

group :jekyll_plugins do
  gem 'jekyll-scholar', '~> 6.6.1'
  gem 'jekyll_picture_tag', :github => 'rbuchberger/jekyll_picture_tag', :branch => 'master'
  gem 'jekyll-twitter-plugin', '~> 2.1'
  gem 'jekyll-last-modified-at', '~> 1.2', '>= 1.2.1'
  gem 'jekyll-redirect-from', '~> 0.16.0'
  gem 'rmagick', '~> 4.1.2'
  gem 'classifier-reborn'
end

group :development do
  gem 'pry'
  gem 'awesome_print'
end
