source "https://rubygems.org"

gem 'jekyll', '~> 4'

group :jekyll_plugins do
  gem 'jekyll-scholar', '~> 6.6.1'
  gem 'jekyll_picture_tag'
  gem 'jekyll-twitter-plugin', '~> 2.1'
  gem 'jekyll-last-modified-at', '~> 1.2', '>= 1.2.1'
  gem 'rmagick', '~> 4.1.2'
  gem 'classifier-reborn'
end
